name: schedule_management
description: A Flutter project for managing schedules.

# Prevent publishing to pub.dev
publish_to: 'none'

# Version details
version: 1.0.0+1

# Flutter SDK constraints
environment:
  sdk: '>=3.4.4 <4.0.0'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Enables localization support
    sdk: flutter
  cached_network_image: ^3.3.1 # For caching network images
  flutter_svg: ^2.0.10+1 # To handle SVG images
  provider: ^6.0.5 # State management solution
  firebase_core: ^3.8.1
  get: ^4.6.6
  shared_preferences: ^2.3.3
  flutter_lints: ^2.0.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1

# Development dependencies for testing
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter-specific configurations
flutter:
  # Asset management
  assets:
    - assets/images/
    - assets/icons/

  # Font management
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600

